image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test

before_script:
  - apk update && apk add --no-cache curl
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

test-job:
  stage: test
  script:
    - docker-compose -f docker/test/docker-compose.yaml down
    - docker-compose -f docker/test/docker-compose.yaml build
    - docker-compose -f docker/test/docker-compose.yaml up --abort-on-container-exit
