image: docker:20.10.7
services:
  - docker:20.10.7-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - test

test-job:
  image: ruby:3.1
  stage: test
  script:
    - apt-get update && apt-get install -y docker-compose
    - docker-compose -f docker/test/docker-compose.yaml down
    - docker-compose -f docker/test/docker-compose.yaml build
    - docker-compose -f docker/test/docker-compose.yaml up --abort-on-container-exit
