image: docker/compose:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - test

test-job:
  stage: test
  script:
    - docker-compose -f docker/test/docker-compose.yaml down
    - docker-compose -f docker/test/docker-compose.yaml build
    - docker-compose -f docker/test/docker-compose.yaml up --abort-on-container-exit
