stages:
  - test

variables:
  TEST_DIR: "src/tests"

test_job:
  stage: test
  image: python:3.11
  before_script:
    - pip install --upgrade pip
    - pip install "poetry==1.6.1"
    - poetry config virtualenvs.create false
    - poetry install
  script:
    - echo "Running tests"
    - pytest $TEST_DIR
  only:
    - branches
  except:
    - tags
