version: '3.7'

services:
  app:
    build: .
    container_name: hh-app
    command: uvicorn main:hh_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/head-hunter
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
      - worker

  db:
    image: postgres
    container_name: hh-db
    environment:
      POSTGRES_DB: hh-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5428:5432"

  redis:
    image: redis
    container_name: hh-redis
    ports:
      - "6379:6379"

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    restart: on-failure
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A api.email.tasks worker -l info
    volumes:
      - .:/head-hunter
    depends_on:
      - rabbitmq
