version: '3.7'

services:
  app:
    build: .
    container_name: hh-app
    command: uvicorn main:hh_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/head-hunter
    ports:
      - "8001:8000"
    depends_on:
      - db
      - rabbitmq
      - worker
      - prometheus
      - grafana

  db:
    image: postgres
    container_name: hh-db
    environment:
      POSTGRES_DB: hh-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5428:5432"

  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3-management
    restart: on-failure
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: celery -A api.email.tasks worker -l info
    volumes:
      - .:/head-hunter
    depends_on:
      - rabbitmq
      - prometheus
      - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"